### ISSUE TITLE
Where does the magic `exp` prop come from?

### ISSUE THREAD

**Issue by bolinfest** [exponentjs/new-project-template#1]
Creating a sample app includes [this line](https://github.com/exponentjs/new-project-template/blob/1b69bff2988b3b592d6e9e494deecefe85845f1b/main.js#L49):

```
let { notification } = this.props.exp;
```

Perhaps it's too early to document, but where does the `exp` prop come from and do all components have it?

**Comment by brentvatne** [comment]
@bolinfest - this is passed in from Exponent to the root component. It has the manifest and a few other things. I've actually removed this from the latest version because it's mainly for internal use and we expose anything important through `Exponent.Constants`. We should probably document it still though: https://github.com/exponentjs/exponent-docs/issues/16
